import React, { useState } from 'react';
import {
  Layers,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Code2,
  ShieldCheck,
  Rocket,
  Activity,
  Cpu,
  FileCode,
  Sparkles,
  GitBranch,
  Terminal,
  Server,
  Lock,
  Play,
  Copy,
  Check,
  RefreshCw,
  Search,
  ExternalLink,
  Info,
  ChevronRight,
  Database,
  BarChart3,
  Sliders,
  Bug,
  Globe
} from 'lucide-react';
import { useAppContext } from '../../context/AppContext';

interface Phase {
  id: number;
  title: string;
  subtitle: string;
  description: string;
  keyAction: string;
  icon: React.ComponentType<{ className?: string }>;
}

export const SDLCProcessHub: React.FC = () => {
  const { speak } = useAppContext();
  const [activePhase, setActivePhase] = useState<number>(1);
  const [completedPhases, setCompletedPhases] = useState<number[]>([1, 2, 3, 4]);
  const [copiedText, setCopiedText] = useState<string | null>(null);

  // Interactive state for tools inside phases
  // Phase 1
  const [reqInput, setReqInput] = useState('Secure user login with password reset');
  const [generatedCriteria, setGeneratedCriteria] = useState<string | null>(null);

  // Phase 4
  const [promptTopic, setPromptTopic] = useState<'auth' | 'validation' | 'rate-limit' | 'architecture'>('auth');

  // Phase 6
  const [testResults, setTestResults] = useState<{ name: string; status: 'pass' | 'fail' | 'running'; duration: string }[] | null>(null);
  const [isTesting, setIsTesting] = useState(false);

  // Phase 7
  const [scanResults, setScanResults] = useState<{ check: string; status: 'passed' | 'warning' | 'failed'; detail: string }[] | null>(null);
  const [isScanning, setIsScanning] = useState(false);

  // Phase 8
  const [deployStep, setDeployStep] = useState<number>(0);
  const [isDeploying, setIsDeploying] = useState(false);

  // Phase 9
  const [logs, setLogs] = useState<string[]>([
    '[03:38:01] INFO  - System boot complete. Service running on port 3000.',
    '[03:38:05] INFO  - Healthcheck /api/health returned 200 OK (3ms)',
    '[03:38:12] DEBUG - Gemini API bridge connected. Model: gemini-3.6-flash',
    '[03:38:20] INFO  - Security audit baseline clean. 0 critical vulnerabilities.'
  ]);

  const phases: Phase[] = [
    {
      id: 1,
      title: 'Idea & Requirements',
      subtitle: 'Define outcomes before writing code',
      description: 'Document explicit problem statements, target personas, and precise acceptance criteria instead of vague promises.',
      keyAction: 'Transform ambiguous goals into measurable, testable acceptance criteria.',
      icon: FileCode
    },
    {
      id: 2,
      title: 'Technology Stack',
      subtitle: 'Deliberate stack selection',
      description: 'Never let AI randomly pick your architecture. Choose reliable, production-tested frameworks matched to project needs.',
      keyAction: 'Select Next.js / React, TypeScript, Tailwind, Supabase/Firebase, Vercel deliberately.',
      icon: Cpu
    },
    {
      id: 3,
      title: 'Design & Architecture',
      subtitle: 'Create system blueprints',
      description: 'Map component relationships, API contracts, folder hierarchies, and database schemas before coding.',
      keyAction: 'Establish clear boundary layers between client UI, server API routes, and database models.',
      icon: Layers
    },
    {
      id: 4,
      title: 'Vibe Coding / Dev',
      subtitle: 'Guided senior AI engineering',
      description: 'Use structured prompts asking AI to act as a Senior Staff Engineer. Require clean code, rate limiting, and zero hardcoded secrets.',
      keyAction: 'Prompt AI with explicit technical standards and full structural context.',
      icon: Code2
    },
    {
      id: 5,
      title: 'Code Review',
      subtitle: 'Never ship raw AI code',
      description: 'Every file generated by AI must be inspected, understood, refactored, and validated by human engineering judgment.',
      keyAction: 'Audit architecture, refactor for readability, enforce error boundaries.',
      icon: Bug
    },
    {
      id: 6,
      title: 'Testing',
      subtitle: 'Automated & edge case validation',
      description: 'Run unit tests (Vitest) and end-to-end scenarios (Playwright). Test bad passwords, expired tokens, and network failures.',
      keyAction: 'Verify normal flows and stress test boundary edge cases.',
      icon: CheckCircle2
    },
    {
      id: 7,
      title: 'Security',
      subtitle: 'Mandatory vulnerability hardening',
      description: 'Audit for hardcoded secrets, plain-text credentials, SQL/NoSQL injection, XSS, and rate limiting gaps.',
      keyAction: 'Run automated vulnerability scans (OWASP ZAP, Semgrep, npm audit).',
      icon: ShieldCheck
    },
    {
      id: 8,
      title: 'Deployment',
      subtitle: 'Automated CI/CD pipeline',
      description: 'Automate build pipeline: GitHub → Cloud Run / Vercel → Database Migrations → Custom Domain with HTTPS.',
      keyAction: 'Store secrets in environment variables, verify HTTPS and SSL certificates.',
      icon: Rocket
    },
    {
      id: 9,
      title: 'Monitoring',
      subtitle: 'Observability & continuous loop',
      description: 'Deployment is not the end. Monitor runtime errors, latency, logs, analytics, and user feedback in real time.',
      keyAction: 'Track exception traces with Sentry and system health metrics.',
      icon: Activity
    }
  ];

  const togglePhaseCompletion = (id: number) => {
    if (completedPhases.includes(id)) {
      setCompletedPhases(completedPhases.filter(p => p !== id));
    } else {
      setCompletedPhases([...completedPhases, id]);
    }
  };

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(label);
    setTimeout(() => setCopiedText(null), 2000);
    speak(`Copied ${label} to clipboard.`);
  };

  const handleGenerateCriteria = () => {
    setGeneratedCriteria(`
❌ Vague Requirement: "${reqInput}"

✅ Professional Acceptance Criteria Blueprint:
1. Authentication:
   - Must use JWT tokens with secure HTTP-only cookies.
   - Passwords MUST be hashed using bcrypt (cost factor >= 12) or Argon2id.
   - Zero plaintext passwords in memory or database.
2. Email Verification:
   - Send 6-digit cryptographically secure verification code via email provider.
   - Code expires strictly after 10 minutes.
3. Security & Rate Limiting:
   - Max 5 failed login attempts per IP per 15-minute window.
   - Trigger IP rate-limit lockout response HTTP 429 with Retry-After header.
4. User Experience:
   - Clear field-level inline error messages for invalid format.
   - Response time under 200ms for auth verification.
    `.trim());
    speak('Generated professional acceptance criteria blueprint.');
  };

  const runSimulatedTests = () => {
    setIsTesting(true);
    setTestResults(null);
    speak('Running automated unit and end-to-end test suite');

    setTimeout(() => {
      setTestResults([
        { name: 'Unit: Auth JWT Verification', status: 'pass', duration: '14ms' },
        { name: 'Unit: Password Hashing Cost Factor', status: 'pass', duration: '120ms' },
        { name: 'Unit: Medical Prescription Validation', status: 'pass', duration: '8ms' },
        { name: 'E2E: Patient Appointment Booking Flow', status: 'pass', duration: '410ms' },
        { name: 'Edge Case: Expired Session Token Rejection', status: 'pass', duration: '18ms' },
        { name: 'Edge Case: Rate Limit 429 Throttle Response', status: 'pass', duration: '22ms' },
        { name: 'Edge Case: SQL/NoSQL Injection Payload Sanitization', status: 'pass', duration: '11ms' }
      ]);
      setIsTesting(false);
      speak('Test suite completed successfully. 7 of 7 tests passed.');
    }, 1200);
  };

  const runSecurityScan = () => {
    setIsScanning(true);
    setScanResults(null);
    speak('Initiating automated security audit and vulnerability scan');

    setTimeout(() => {
      setScanResults([
        { check: 'Hardcoded Secrets Check', status: 'passed', detail: 'Zero plain-text API keys or DB passwords detected in source tree.' },
        { check: 'OWASP Top 10 Vulnerabilities', status: 'passed', detail: 'Input sanitization active. XSS and Injection payloads rejected.' },
        { check: 'Dependency Vulnerability Audit (npm audit)', status: 'passed', detail: '0 High, 0 Critical vulnerabilities in package dependencies.' },
        { check: 'Rate Limiting Guardrails', status: 'passed', detail: 'Express rate-limiter middleware detected on sensitive /api endpoints.' },
        { check: 'HTTPS & TLS Transport Policy', status: 'passed', detail: 'HSTS header enforced. SSL grade A+ active.' },
        { check: 'Database Access Policy (RLS / Rules)', status: 'warning', detail: 'Verify guest role permissions on audit logs table.' }
      ]);
      setIsScanning(false);
      speak('Security audit complete. No critical vulnerabilities found.');
    }, 1500);
  };

  const runDeploymentSimulation = () => {
    setIsDeploying(true);
    setDeployStep(1);
    speak('Starting deployment pipeline');

    const steps = [
      'Linking GitHub repository trigger...',
      'Building production container (npm run build)...',
      'Running database schema migration check...',
      'Injecting environment variables & API keys...',
      'Deploying build artifact to Cloud Run container on Port 3000...',
      'Binding SSL HTTPS custom domain...'
    ];

    let current = 1;
    const interval = setInterval(() => {
      current++;
      if (current <= steps.length) {
        setDeployStep(current);
      } else {
        clearInterval(interval);
        setIsDeploying(false);
        speak('Deployment pipeline finished successfully!');
      }
    }, 800);
  };

  const compliancePercentage = Math.round((completedPhases.length / phases.length) * 100);

  return (
    <div className="space-y-6 pb-12 font-mono">
      {/* Top Banner Header */}
      <div className="bg-white border-4 border-[#1A1A1A] p-6 shadow-[6px_6px_0px_0px_#1A1A1A]">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 border-b-2 border-[#1A1A1A] pb-6">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <div className="w-10 h-10 bg-[#1A1A1A] text-white flex items-center justify-center font-black border-2 border-[#1A1A1A]">
                <GitBranch className="w-6 h-6 text-[#BC544B]" />
              </div>
              <div>
                <h1 className="text-2xl font-black uppercase text-[#1A1A1A] tracking-tight">The 9-Phase Development Standard</h1>
                <p className="text-xs text-[#1A1A1A]/70 uppercase font-bold">Engineering Governance • Quality Assurance • Vibe Coding Discipline</p>
              </div>
            </div>
            <p className="text-xs text-[#1A1A1A] max-w-3xl leading-relaxed">
              "Don't ask AI to build your project for you. Ask AI to help you build your project."
              Use AI to accelerate execution while maintaining strict human control over requirements, architecture, code review, security, and deployment.
            </p>
          </div>

          {/* Compliance Widget */}
          <div className="bg-[#F8F7F4] border-2 border-[#1A1A1A] p-4 flex flex-col justify-between min-w-[240px]">
            <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2 mb-2">
              <span className="text-[10px] font-black uppercase text-[#1A1A1A]/70">Compliance Score</span>
              <span className="text-xs font-black bg-[#1A1A1A] text-white px-2 py-0.5">{compliancePercentage}%</span>
            </div>
            <div className="w-full bg-[#1A1A1A]/20 h-4 border border-[#1A1A1A] mb-2 overflow-hidden">
              <div
                className="h-full bg-[#BC544B] transition-all duration-500"
                style={{ width: `${compliancePercentage}%` }}
              />
            </div>
            <p className="text-[10px] font-bold uppercase text-[#1A1A1A] text-center">
              {completedPhases.length} of {phases.length} SDLC Phases Verified
            </p>
          </div>
        </div>

        {/* Phase Navigator Bar */}
        <div className="grid grid-cols-3 sm:grid-cols-5 lg:grid-cols-9 gap-2 mt-6">
          {phases.map(phase => {
            const Icon = phase.icon;
            const isSelected = activePhase === phase.id;
            const isDone = completedPhases.includes(phase.id);

            return (
              <button
                key={phase.id}
                onClick={() => {
                  setActivePhase(phase.id);
                  speak(`Switched to Phase ${phase.id}: ${phase.title}`);
                }}
                className={`p-2 border-2 border-[#1A1A1A] text-left transition-all flex flex-col justify-between h-20 ${
                  isSelected
                    ? 'bg-[#1A1A1A] text-white shadow-[3px_3px_0px_0px_#BC544B]'
                    : isDone
                    ? 'bg-[#F8F7F4] text-[#1A1A1A] hover:bg-[#1A1A1A] hover:text-white'
                    : 'bg-white text-[#1A1A1A]/60 hover:bg-[#F8F7F4]'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className={`text-[10px] font-black px-1 ${isSelected ? 'bg-[#BC544B] text-white' : 'bg-[#1A1A1A] text-white'}`}>
                    P{phase.id}
                  </span>
                  {isDone && <Check className="w-3.5 h-3.5 text-[#BC544B]" />}
                </div>
                <div className="mt-1">
                  <Icon className={`w-4 h-4 mb-1 ${isSelected ? 'text-[#BC544B]' : 'text-current'}`} />
                  <p className="text-[9px] font-black uppercase leading-tight truncate">{phase.title}</p>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Active Phase Main Content Section */}
      {(() => {
        const currentPhaseObj = phases.find(p => p.id === activePhase)!;
        const Icon = currentPhaseObj.icon;
        const isPhaseDone = completedPhases.includes(currentPhaseObj.id);

        return (
          <div className="bg-white border-4 border-[#1A1A1A] p-6 shadow-[6px_6px_0px_0px_#1A1A1A] space-y-6">
            {/* Phase Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b-2 border-[#1A1A1A] pb-4">
              <div className="flex items-start space-x-3">
                <div className="w-12 h-12 bg-[#1A1A1A] text-white flex items-center justify-center font-black border-2 border-[#1A1A1A] flex-shrink-0">
                  <Icon className="w-6 h-6 text-[#BC544B]" />
                </div>
                <div>
                  <div className="flex items-center space-x-2">
                    <span className="text-xs font-black bg-[#BC544B] text-white px-2 py-0.5 uppercase">Phase {currentPhaseObj.id}</span>
                    <h2 className="text-xl font-black uppercase text-[#1A1A1A]">{currentPhaseObj.title}</h2>
                  </div>
                  <p className="text-xs font-bold text-[#1A1A1A]/70 uppercase mt-0.5">{currentPhaseObj.subtitle}</p>
                </div>
              </div>

              <div className="flex items-center space-x-3">
                <button
                  onClick={() => togglePhaseCompletion(currentPhaseObj.id)}
                  className={`px-4 py-2 border-2 border-[#1A1A1A] text-xs font-black uppercase transition-all flex items-center space-x-2 ${
                    isPhaseDone
                      ? 'bg-[#1A1A1A] text-white'
                      : 'bg-[#F8F7F4] text-[#1A1A1A] hover:bg-[#1A1A1A] hover:text-white'
                  }`}
                >
                  {isPhaseDone ? <Check className="w-4 h-4 text-[#BC544B]" /> : <XCircle className="w-4 h-4" />}
                  <span>{isPhaseDone ? 'Phase Verified ✓' : 'Mark Phase Completed'}</span>
                </button>
              </div>
            </div>

            {/* Overview Box */}
            <div className="p-4 bg-[#F8F7F4] border-2 border-[#1A1A1A] space-y-2">
              <h3 className="text-xs font-black uppercase text-[#1A1A1A]">Core Directive:</h3>
              <p className="text-xs text-[#1A1A1A] leading-relaxed">{currentPhaseObj.description}</p>
              <p className="text-xs text-[#BC544B] font-bold uppercase mt-1">★ Key Action: {currentPhaseObj.keyAction}</p>
            </div>

            {/* Dynamic Interactive Phase Tool Module */}
            {activePhase === 1 && (
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 1 Interactive Tool: Requirements & Acceptance Criteria Formulator</h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 border-2 border-[#1A1A1A] bg-white space-y-3">
                    <label className="block text-xs font-bold uppercase text-[#1A1A1A]">Input High-Level Requirement / Feature:</label>
                    <input
                      type="text"
                      value={reqInput}
                      onChange={e => setReqInput(e.target.value)}
                      className="w-full p-2 border-2 border-[#1A1A1A] bg-[#F8F7F4] text-xs font-bold text-[#1A1A1A]"
                      placeholder="e.g. Patient appointment scheduling with SMS alert"
                    />

                    <button
                      onClick={handleGenerateCriteria}
                      className="w-full bg-[#BC544B] hover:bg-[#a3443c] text-white font-black text-xs py-2.5 border-2 border-[#1A1A1A] uppercase tracking-wider transition-colors"
                    >
                      Generate Precise Acceptance Criteria
                    </button>

                    <div className="p-3 bg-[#F8F7F4] border border-[#1A1A1A] text-[11px] space-y-1">
                      <p className="font-bold text-[#1A1A1A] uppercase">Rule of Thumb:</p>
                      <p className="text-[#1A1A1A]/80">Never accept vague inputs like "Make login secure". Define explicit JWT algorithms, bcrypt cost factors, rate limits, and verification expiration times.</p>
                    </div>
                  </div>

                  <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-3 font-mono">
                    <div className="flex items-center justify-between border-b border-white/20 pb-2">
                      <span className="text-xs font-bold text-[#BC544B] uppercase">Output Specification</span>
                      {generatedCriteria && (
                        <button
                          onClick={() => copyToClipboard(generatedCriteria, 'Acceptance Criteria')}
                          className="text-[10px] bg-white text-[#1A1A1A] px-2 py-0.5 font-bold uppercase hover:bg-[#BC544B] hover:text-white"
                        >
                          {copiedText === 'Acceptance Criteria' ? 'Copied ✓' : 'Copy Spec'}
                        </button>
                      )}
                    </div>

                    <pre className="text-xs text-emerald-400 whitespace-pre-wrap leading-relaxed">
                      {generatedCriteria || 'Click "Generate Precise Acceptance Criteria" to formulate structured acceptance specifications.'}
                    </pre>
                  </div>
                </div>
              </div>
            )}

            {activePhase === 2 && (
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 2 Interactive Matrix: Stack Comparison & CareFlow Architecture</h3>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  {/* Recommended Standard Stack */}
                  <div className="p-4 border-2 border-[#1A1A1A] bg-white space-y-3">
                    <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2">
                      <h4 className="font-black text-xs uppercase text-[#1A1A1A]">Recommended Standard Stack (Guide)</h4>
                      <span className="text-[10px] bg-[#1A1A1A] text-white font-bold px-2 py-0.5 uppercase">Primary</span>
                    </div>

                    <ul className="text-xs space-y-2">
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">Framework & Meta:</span>
                        <span className="font-mono text-[#BC544B] font-bold">Next.js / Vite React</span>
                      </li>
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">Type System:</span>
                        <span className="font-mono text-[#1A1A1A] font-bold">TypeScript (Strict)</span>
                      </li>
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">Styling Engine:</span>
                        <span className="font-mono text-[#1A1A1A] font-bold">Tailwind CSS</span>
                      </li>
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">Database & Auth:</span>
                        <span className="font-mono text-[#1A1A1A] font-bold">Supabase / Firebase</span>
                      </li>
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">ORM Layer:</span>
                        <span className="font-mono text-[#1A1A1A] font-bold">Prisma / Drizzle</span>
                      </li>
                      <li className="flex items-center justify-between p-2 bg-[#F8F7F4] border border-[#1A1A1A]">
                        <span className="font-bold text-[#1A1A1A]">Deployment:</span>
                        <span className="font-mono text-[#1A1A1A] font-bold">Vercel / Cloud Run</span>
                      </li>
                    </ul>
                  </div>

                  {/* CareFlow AI Active Runtime Stack */}
                  <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-3">
                    <div className="flex items-center justify-between border-b border-white/20 pb-2">
                      <h4 className="font-black text-xs uppercase text-white">CareFlow AI Runtime Stack Telemetry</h4>
                      <span className="text-[10px] bg-[#BC544B] text-white font-black px-2 py-0.5 uppercase">LIVE</span>
                    </div>

                    <div className="space-y-2 text-xs">
                      <div className="p-2 border border-white/20 bg-white/5 flex items-center justify-between">
                        <span>Frontend UI:</span>
                        <span className="text-emerald-400 font-bold">React 18 + Vite 5 + Tailwind v4</span>
                      </div>
                      <div className="p-2 border border-white/20 bg-white/5 flex items-center justify-between">
                        <span>Server Architecture:</span>
                        <span className="text-emerald-400 font-bold">Node.js Express + Port 3000 Router</span>
                      </div>
                      <div className="p-2 border border-white/20 bg-white/5 flex items-center justify-between">
                        <span>AI Intelligence SDK:</span>
                        <span className="text-[#BC544B] font-bold">@google/genai (Gemini 3.6 Flash)</span>
                      </div>
                      <div className="p-2 border border-white/20 bg-white/5 flex items-center justify-between">
                        <span>Data Visuals:</span>
                        <span className="text-emerald-400 font-bold">Recharts + Lucide Icons</span>
                      </div>
                      <div className="p-2 border border-white/20 bg-white/5 flex items-center justify-between">
                        <span>Container Deployment:</span>
                        <span className="text-emerald-400 font-bold">Cloud Run Sandbox Container</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {activePhase === 3 && (
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 3 Architecture Blueprint & System Topology</h3>

                <div className="p-4 border-2 border-[#1A1A1A] bg-[#F8F7F4] space-y-4">
                  <p className="text-xs text-[#1A1A1A] font-bold uppercase">System Architecture Flow Diagram:</p>

                  <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-center text-xs">
                    <div className="p-3 bg-white border-2 border-[#1A1A1A] shadow-[2px_2px_0px_0px_#1A1A1A]">
                      <Globe className="w-5 h-5 mx-auto mb-1 text-[#BC544B]" />
                      <p className="font-black uppercase text-[#1A1A1A]">Client Layer</p>
                      <p className="text-[10px] text-[#1A1A1A]/70 uppercase mt-1">React SPA • TailWind UI • Voice Guidance</p>
                    </div>

                    <div className="p-3 bg-white border-2 border-[#1A1A1A] shadow-[2px_2px_0px_0px_#1A1A1A]">
                      <Server className="w-5 h-5 mx-auto mb-1 text-[#1A1A1A]" />
                      <p className="font-black uppercase text-[#1A1A1A]">API Gateway</p>
                      <p className="text-[10px] text-[#1A1A1A]/70 uppercase mt-1">Express Router • Rate Limiter • Auth Proxy</p>
                    </div>

                    <div className="p-3 bg-white border-2 border-[#1A1A1A] shadow-[2px_2px_0px_0px_#1A1A1A]">
                      <Cpu className="w-5 h-5 mx-auto mb-1 text-[#BC544B]" />
                      <p className="font-black uppercase text-[#1A1A1A]">AI Bridge</p>
                      <p className="text-[10px] text-[#1A1A1A]/70 uppercase mt-1">@google/genai • Gemini 3.6 Flash Server Key</p>
                    </div>

                    <div className="p-3 bg-white border-2 border-[#1A1A1A] shadow-[2px_2px_0px_0px_#1A1A1A]">
                      <Database className="w-5 h-5 mx-auto mb-1 text-[#1A1A1A]" />
                      <p className="font-black uppercase text-[#1A1A1A]">Data State</p>
                      <p className="text-[10px] text-[#1A1A1A]/70 uppercase mt-1">AppContext Store • Firestore / Persistence</p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {activePhase === 4 && (
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 4 Interactive Senior Engineer AI Prompt Generator</h3>

                <div className="flex space-x-2 border-b-2 border-[#1A1A1A] pb-2">
                  {(['auth', 'validation', 'rate-limit', 'architecture'] as const).map(t => (
                    <button
                      key={t}
                      onClick={() => setPromptTopic(t)}
                      className={`px-3 py-1.5 border-2 border-[#1A1A1A] text-xs font-bold uppercase transition-all ${
                        promptTopic === t ? 'bg-[#1A1A1A] text-white' : 'bg-[#F8F7F4] text-[#1A1A1A]'
                      }`}
                    >
                      {t.replace('-', ' ')}
                    </button>
                  ))}
                </div>

                <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-3">
                  <div className="flex items-center justify-between border-b border-white/20 pb-2">
                    <span className="text-xs font-bold text-emerald-400 uppercase">Senior AI Prompt Template ({promptTopic})</span>
                    <button
                      onClick={() => {
                        const t = promptTopic === 'auth'
                          ? `Act as a Senior Staff Engineer. Write a secure authentication module using Express and TypeScript. Ensure JWT tokens are stored in HTTP-only cookies, password hashing uses bcrypt cost 12, zero hardcoded secrets, and clear error boundaries.`
                          : promptTopic === 'validation'
                          ? `Act as a Senior Staff Engineer. Implement strict Zod schema validation middleware for all POST /api endpoints. Reject malformed payloads with 400 Bad Request and detailed field-level error messages.`
                          : promptTopic === 'rate-limit'
                          ? `Act as a Senior Staff Engineer. Add rate limiting middleware using express-rate-limit to protect authentication and AI routes against brute-force attacks.`
                          : `Act as a Senior Staff Engineer. Modularize the application structure separating components, services, context hooks, and types cleanly. Maintain strict TypeScript types.`;
                        copyToClipboard(t, 'AI Prompt');
                      }}
                      className="text-[10px] bg-white text-[#1A1A1A] px-2.5 py-1 font-bold uppercase hover:bg-[#BC544B] hover:text-white transition-colors"
                    >
                      {copiedText === 'AI Prompt' ? 'Copied ✓' : 'Copy Prompt'}
                    </button>
                  </div>

                  <pre className="text-xs text-emerald-400 whitespace-pre-wrap leading-relaxed font-mono">
                    {promptTopic === 'auth' && `Act as a Senior Staff Engineer. Write a secure authentication module using Express and TypeScript.

Mandatory Requirements:
1. Store JWT tokens in HTTP-only, SameSite=Strict cookies.
2. Hash passwords with bcrypt (cost factor >= 12). Never store or log plain text passwords.
3. Include rate-limiting on /api/auth/login (max 5 attempts per 15 min).
4. Implement protected route middleware verifying token signatures.
5. Provide comprehensive error handling and return clear JSON error structures.`}

                    {promptTopic === 'validation' && `Act as a Senior Staff Engineer. Implement strict Zod schema validation middleware for all POST /api endpoints.

Mandatory Requirements:
1. Define strict type-safe schemas for inputs (e.g. Email, Password, Patient ID, Prescriptions).
2. Intercept requests before business logic.
3. If invalid, return HTTP 400 with field-level error diagnostics.
4. Sanitize strings against XSS and HTML injection.`}

                    {promptTopic === 'rate-limit' && `Act as a Senior Staff Engineer. Add rate limiting middleware to express.

Mandatory Requirements:
1. Use express-rate-limit.
2. Limit public API routes to 100 requests per 15 minutes per IP.
3. Limit AI inference endpoints to 10 requests per minute per user.
4. Return HTTP 429 with standard Retry-After header when exceeded.`}

                    {promptTopic === 'architecture' && `Act as a Senior Staff Engineer. Structure a full-stack React + Express + TypeScript codebase.

Mandatory Requirements:
1. Clean separation of concerns: /src/components, /src/context, /src/types.ts, /server.ts.
2. Zero circular dependencies.
3. Server-side API key protection for Gemini & third-party keys.
4. Strict TypeScript configuration without 'any' types.`}
                  </pre>
                </div>
              </div>
            )}

            {activePhase === 5 && (
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 5 Code Review: "Never Ship Raw AI Code"</h3>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Bad Raw AI Code */}
                  <div className="p-4 border-2 border-[#1A1A1A] bg-red-50/50 space-y-2">
                    <div className="flex items-center space-x-2 text-red-700 font-black text-xs uppercase border-b border-red-200 pb-2">
                      <XCircle className="w-4 h-4" />
                      <span>❌ Raw AI Code (Unreviewed)</span>
                    </div>
                    <pre className="text-[11px] font-mono text-red-900 bg-white p-3 border border-red-200 overflow-x-auto">
{`// BAD: Hardcoded secrets & no error checks
const key = "AIzaSyA_SECRET_KEY_123";
app.post("/login", (req, res) => {
  const { user, pass } = req.body;
  // Dangerous plain text query!
  db.query("SELECT * FROM users WHERE u='" + user + "'");
  res.send({ status: "ok" });
});`}
                    </pre>
                  </div>

                  {/* Refactored Senior Code */}
                  <div className="p-4 border-2 border-[#1A1A1A] bg-emerald-50/50 space-y-2">
                    <div className="flex items-center space-x-2 text-emerald-800 font-black text-xs uppercase border-b border-emerald-200 pb-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                      <span>✅ Senior Refactored Code</span>
                    </div>
                    <pre className="text-[11px] font-mono text-emerald-900 bg-white p-3 border border-emerald-200 overflow-x-auto">
{`// GOOD: Environment key + parameterized query + rate limiter
const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) throw new Error("GEMINI_API_KEY missing");

app.post("/login", loginRateLimiter, async (req, res) => {
  const { user, pass } = authSchema.parse(req.body);
  const userRecord = await db.findUser(user);
  const isValid = await bcrypt.compare(pass, userRecord.hash);
  if (!isValid) return res.status(401).json({ error: "Invalid credentials" });
  res.json({ token: generateSecureJWT(userRecord.id) });
});`}
                    </pre>
                  </div>
                </div>
              </div>
            )}

            {activePhase === 6 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2">
                  <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 6 Automated Test Runner (Vitest & Playwright Simulation)</h3>
                  <button
                    onClick={runSimulatedTests}
                    disabled={isTesting}
                    className="bg-[#BC544B] hover:bg-[#a3443c] text-white font-black text-xs px-4 py-2 border-2 border-[#1A1A1A] uppercase tracking-wider transition-colors flex items-center space-x-2 disabled:opacity-50"
                  >
                    {isTesting ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-current" />}
                    <span>{isTesting ? 'Running Test Suite...' : 'Execute Full Test Suite'}</span>
                  </button>
                </div>

                {testResults ? (
                  <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-2">
                    <div className="flex items-center justify-between border-b border-white/20 pb-2 text-xs font-bold uppercase text-emerald-400">
                      <span>Test Execution Results</span>
                      <span>7 / 7 PASSED (100%)</span>
                    </div>
                    <div className="space-y-1 text-xs">
                      {testResults.map((t, idx) => (
                        <div key={idx} className="flex items-center justify-between p-2 bg-white/5 border border-white/10 font-mono">
                          <span className="text-emerald-400 font-bold">✓ {t.name}</span>
                          <span className="text-white/60 text-[10px]">{t.duration}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="p-6 border-2 border-[#1A1A1A] bg-[#F8F7F4] text-center text-xs font-bold uppercase text-[#1A1A1A]/70">
                    Click "Execute Full Test Suite" to simulate automated unit testing and end-to-end edge case validation.
                  </div>
                )}
              </div>
            )}

            {activePhase === 7 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2">
                  <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 7 Security & Vulnerability Audit Scanner</h3>
                  <button
                    onClick={runSecurityScan}
                    disabled={isScanning}
                    className="bg-[#1A1A1A] hover:bg-black text-white font-black text-xs px-4 py-2 border-2 border-[#1A1A1A] uppercase tracking-wider transition-colors flex items-center space-x-2 disabled:opacity-50"
                  >
                    {isScanning ? <RefreshCw className="w-4 h-4 animate-spin text-[#BC544B]" /> : <ShieldCheck className="w-4 h-4 text-[#BC544B]" />}
                    <span>{isScanning ? 'Scanning Codebase...' : 'Run Security Audit'}</span>
                  </button>
                </div>

                {scanResults ? (
                  <div className="space-y-2">
                    {scanResults.map((s, idx) => (
                      <div key={idx} className="p-3 border-2 border-[#1A1A1A] bg-white flex items-start justify-between gap-4 text-xs font-mono">
                        <div>
                          <div className="flex items-center space-x-2">
                            <span className="font-black text-[#1A1A1A] uppercase">{s.check}</span>
                            <span className={`text-[10px] font-bold px-2 py-0.5 border border-[#1A1A1A] uppercase ${
                              s.status === 'passed' ? 'bg-[#1A1A1A] text-white' : 'bg-[#BC544B] text-white'
                            }`}>
                              {s.status}
                            </span>
                          </div>
                          <p className="text-[11px] text-[#1A1A1A]/80 mt-1">{s.detail}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="p-6 border-2 border-[#1A1A1A] bg-[#F8F7F4] text-center text-xs font-bold uppercase text-[#1A1A1A]/70">
                    Click "Run Security Audit" to execute automated OWASP, Semgrep, and secret leaks analysis.
                  </div>
                )}
              </div>
            )}

            {activePhase === 8 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2">
                  <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 8 CI/CD Deployment Pipeline Visualizer</h3>
                  <button
                    onClick={runDeploymentSimulation}
                    disabled={isDeploying}
                    className="bg-[#BC544B] hover:bg-[#a3443c] text-white font-black text-xs px-4 py-2 border-2 border-[#1A1A1A] uppercase tracking-wider transition-colors flex items-center space-x-2 disabled:opacity-50"
                  >
                    <Rocket className="w-4 h-4" />
                    <span>{isDeploying ? 'Deploying...' : 'Trigger Production Deploy'}</span>
                  </button>
                </div>

                <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-3 font-mono text-xs">
                  <div className="flex items-center justify-between border-b border-white/20 pb-2">
                    <span className="text-emerald-400 font-bold uppercase">Pipeline: GitHub → Cloud Run (Port 3000)</span>
                    <span className="text-[10px] bg-white text-[#1A1A1A] font-bold px-2 py-0.5 uppercase">Status: {isDeploying ? 'IN PROGRESS' : deployStep > 0 ? 'SUCCESS' : 'READY'}</span>
                  </div>

                  <div className="space-y-2">
                    {[
                      '1. Linking GitHub repository trigger',
                      '2. Building production container (npm run build)',
                      '3. Running database schema migration check',
                      '4. Injecting environment variables & API keys',
                      '5. Deploying build artifact to Cloud Run container on Port 3000',
                      '6. Binding SSL HTTPS custom domain'
                    ].map((stepStr, idx) => {
                      const stepNum = idx + 1;
                      const isFinished = deployStep >= stepNum;
                      const isCurrent = deployStep === stepNum && isDeploying;

                      return (
                        <div key={idx} className={`p-2.5 border flex items-center justify-between ${
                          isFinished
                            ? 'border-emerald-500 bg-emerald-500/10 text-emerald-400'
                            : isCurrent
                            ? 'border-[#BC544B] bg-[#BC544B]/20 text-white animate-pulse'
                            : 'border-white/10 text-white/40'
                        }`}>
                          <span>{stepStr}</span>
                          <span className="font-bold text-[10px]">
                            {isFinished ? '✓ PASSED' : isCurrent ? 'RUNNING...' : 'WAITING'}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {activePhase === 9 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b-2 border-[#1A1A1A] pb-2">
                  <h3 className="text-sm font-black uppercase text-[#1A1A1A]">Phase 9 Monitoring, Telemetry & Sentry Log Console</h3>
                  <button
                    onClick={() => {
                      const time = new Date().toLocaleTimeString();
                      setLogs(prev => [
                        `[${time}] INFO  - Patient consultation queue ping. Latency: 12ms`,
                        ...prev
                      ]);
                      speak('Pings logged.');
                    }}
                    className="bg-[#1A1A1A] hover:bg-black text-white font-black text-xs px-3 py-1.5 border-2 border-[#1A1A1A] uppercase"
                  >
                    Simulate System Ping
                  </button>
                </div>

                <div className="p-4 border-2 border-[#1A1A1A] bg-[#1A1A1A] text-white space-y-2 font-mono text-xs">
                  <div className="flex items-center justify-between border-b border-white/20 pb-2 text-emerald-400 font-bold uppercase">
                    <span>Live Cloud Log Telemetry Stream</span>
                    <span className="animate-pulse text-[#BC544B]">● LIVE MONITORING</span>
                  </div>

                  <div className="space-y-1.5 max-h-60 overflow-y-auto pr-2">
                    {logs.map((log, idx) => (
                      <div key={idx} className="p-2 bg-white/5 border border-white/10 text-emerald-300">
                        {log}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        );
      })()}
    </div>
  );
};
