import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const MedicalDisclaimer: React.FC<{ compact?: boolean }> = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="flex items-center space-x-2 text-[11px] font-medium text-slate-600 bg-slate-50 px-3 py-2 rounded-xl border border-slate-200">
        <ShieldAlert className="w-3.5 h-3.5 text-amber-600 flex-shrink-0" />
        <span>AI outputs are for guidance only. Consult a licensed physician for medical diagnosis.</span>
      </div>
    );
  }

  return (
    <div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-4 flex items-start space-x-3 text-xs text-slate-700">
      <ShieldAlert className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
      <div>
        <span className="font-bold block uppercase tracking-wider text-amber-900 mb-0.5">Clinical AI Advisory & Medical Disclaimer</span>
        <p className="text-slate-600 leading-relaxed text-[11px]">
          CareFlow AI outputs, symptom explanations, and lab report summarizations are generated by intelligence models for informational support only. This application does not replace professional medical advice, diagnosis, or treatment. In case of a medical emergency, immediately dial your local emergency services (911).
        </p>
      </div>
    </div>
  );
};
